--[[
p = peripheral.wrap("left")
function harvest()
    p.use("block", "down")
    turtle.forward()
    sleep(1)
    p.use("block", "down")
    sleep(1)
    turtle.forward()
    sleep(1)
    p.use("block", "down")
    sleep(1)
    turtle.forward()
    sleep(1)
    p.use("block", "down")
    sleep(1)
    turtle.forward()
    sleep(1)
    p.use("block", "down")
    sleep(1)
end
function left()
   turtle.turnLeft()
   turtle.forward()
   turtle.forward()
   turtle.turnLeft()
end
function right()
   turtle.turnRight()
   turtle.forward()
   turtle.turnRight()
end
function drop()
   	turtle.select(1)
	turtle.dropUp()
	turtle.select(2)
	turtle.dropUp()
	turtle.select(3)
	turtle.dropUp()
	turtle.select(4)
	turtle.dropUp()
	turtle.select(5)
	turtle.dropUp()
	turtle.select(6)
	turtle.dropUp()
	turtle.select(7)
	turtle.dropUp()
	turtle.select(8)
	turtle.dropUp()
	turtle.select(9)
	turtle.dropUp()
	turtle.select(10)
	turtle.dropUp()
	turtle.select(11)
	turtle.dropUp()
	turtle.select(12)
	turtle.dropUp()
	turtle.select(13)
	turtle.dropUp()
	turtle.select(14)
	turtle.dropUp()
	turtle.select(15)
	turtle.dropUp()
	turtle.select(16)
	turtle.dropUp()
end

function treturn()
   	turtle.turnRight()
	turtle.turnRight()
	turtle.forward()
	turtle.turnRight()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	--]]
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.forward()
	turtle.turnRight()
	turtle.forward()
	turtle.turnLeft()
	turtle.turnLeft()
[[--

end

harvest()
left()
harvest()
right()
harvest()
left()
harvest()
right()
harvest()
left()
harvest()
right()
harvest()
left()
harvest()
right()
harvest()
left()
harvest()
right()
harvest()
left()
harvest()
right()
harvest()
left()
harvest()
drop()
--]]

right()
harvest()
left()
harvest()
right()
harvest()
left()
harvest()
right()
harvest()
left()
harvest()
drop()
treturn()
